Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\MySite\OnlineSchool\main\views.py changed, reloading.
D:\MySite\OnlineSchool\main\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\MySite\OnlineSchool\main\models.py changed, reloading.
D:\MySite\OnlineSchool\main\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\MySite\OnlineSchool\main\views.py changed, reloading.
D:\MySite\OnlineSchool\main\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 8513
"GET / HTTP/1.1" 200 8513
Internal Server Error: /courses/
Traceback (most recent call last):
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: ОШИБКА:  столбец courses.duration не существует
LINE 1: ...urses"."dfficulty_level", "courses"."id_teacher", "courses"....
                                                             ^
HINT:  Возможно, предполагалась ссылка на столбец "courses.duraction".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MySite\OnlineSchool\main\views.py", line 65, in courses
    for course in courses_list:
                  ^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: ОШИБКА:  столбец courses.duration не существует
LINE 1: ...urses"."dfficulty_level", "courses"."id_teacher", "courses"....
                                                             ^
HINT:  Возможно, предполагалась ссылка на столбец "courses.duraction".

Internal Server Error: /courses/
Traceback (most recent call last):
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: ОШИБКА:  столбец courses.duration не существует
LINE 1: ...urses"."dfficulty_level", "courses"."id_teacher", "courses"....
                                                             ^
HINT:  Возможно, предполагалась ссылка на столбец "courses.duraction".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MySite\OnlineSchool\main\views.py", line 65, in courses
    for course in courses_list:
                  ^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\sofa1\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: ОШИБКА:  столбец courses.duration не существует
LINE 1: ...urses"."dfficulty_level", "courses"."id_teacher", "courses"....
                                                             ^
HINT:  Возможно, предполагалась ссылка на столбец "courses.duraction".

"GET /courses/ HTTP/1.1" 500 124135
"GET /courses/ HTTP/1.1" 500 124135
D:\MySite\OnlineSchool\main\urls.py changed, reloading.
D:\MySite\OnlineSchool\main\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\MySite\OnlineSchool\main\views.py changed, reloading.
D:\MySite\OnlineSchool\main\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\MySite\OnlineSchool\OnlineSchool\settings.py changed, reloading.
D:\MySite\OnlineSchool\OnlineSchool\settings.py changed, reloading.
